@startuml


class DBaseController {
    List<DBase> dBases;

    void collectDB(title, country);
    List<Vacancy> getVacancies();
    void clearDBases();
}

interface DBase {
    void dropDB();
    void collectDB(String... queryParams);
    List<Vacancy> getAllRecords();
}

class HHdbase
class LIdbase

DBase <|-- HHdbase
DBase <|-- LIdbase

@enduml